In [1]:
import pandas as pd
import numpy as np

In [84]:
df = pd.read_excel('data/sms_strong_signal_1000.xlsx')

In [82]:
df.head()

,message_id,country,operator,sender_id,route,message_length,time_of_day,campaign_type,historical_delivery_rate,previous_failures,delivery_status
0,0,UK,vodafone,BANKTX,domestic,53,afternoon,promo,0.79,5,failed
1,1,IN,jio,BANKTX,domestic,296,evening,alert,0.72,1,failed
2,2,UK,jio,BANKTX,intl,196,afternoon,otp,0.62,3,failed
3,3,UK,airtel,PAYAPP,domestic,278,night,alert,0.98,1,delivered
4,4,UK,vodafone,SHOPPY,intl,136,morning,otp,0.64,1,delivered

In [45]:
df.drop(['message_id'], axis=1, inplace=True)

In [46]:
df.columns

Index(['country', 'operator', 'sender_id', 'route', 'message_length',
       'time_of_day', 'campaign_type', 'historical_delivery_rate',
       'previous_failures', 'delivery_status'],
      dtype='str')

In [47]:
df['delivery_status'] = df['delivery_status'].map({
    'delivered': 1,
    'failed': 0
})

In [48]:
df['operator'].value_counts()

operator
jio         279
vodafone    253
airtel      246
verizon     222
Name: count, dtype: int64

In [49]:
df['sender_id'].value_counts()

sender_id
PAYAPP    354
SHOPPY    327
BANKTX    319
Name: count, dtype: int64

In [50]:
df['country'].value_counts()

country
UK    360
IN    342
US    298
Name: count, dtype: int64

In [51]:
df['previous_failures'].value_counts()

previous_failures
0    178
2    175
1    169
5    168
4    156
3    154
Name: count, dtype: int64

In [52]:
df['campaign_type'].value_counts()

campaign_type
otp      345
alert    336
promo    319
Name: count, dtype: int64

Understanding the impact of features on our delivery_status

In [53]:
print(df.groupby('campaign_type')['delivery_status'].mean())
print(df.groupby('route')['delivery_status'].mean())
print(df.groupby('operator')['delivery_status'].mean())
print(df.groupby('time_of_day')['delivery_status'].mean())
print(df.groupby('previous_failures')['delivery_status'].mean())

campaign_type
alert    0.494048
otp      0.611594
promo    0.231975
Name: delivery_status, dtype: float64
route
domestic    0.474895
intl        0.429119
Name: delivery_status, dtype: float64
operator
airtel      0.439024
jio         0.494624
verizon     0.418919
vodafone    0.442688
Name: delivery_status, dtype: float64
time_of_day
afternoon    0.501961
evening      0.456747
morning      0.436441
night        0.400000
Name: delivery_status, dtype: float64
previous_failures
0    0.584270
1    0.544379
2    0.520000
3    0.357143
4    0.391026
5    0.285714
Name: delivery_status, dtype: float64

In [54]:
df.groupby('previous_failures')['delivery_status'].count()

previous_failures
0    178
1    169
2    175
3    154
4    156
5    168
Name: delivery_status, dtype: int64

In [55]:
# continous features
df['rate_bin'] = pd.cut(df['historical_delivery_rate'], bins=3)

In [56]:
df.groupby('rate_bin')['delivery_status'].mean()

rate_bin
(0.5, 0.663]      0.284916
(0.663, 0.827]    0.444444
(0.827, 0.99]     0.633929
Name: delivery_status, dtype: float64

In [57]:
# continous features
df['length_bin'] = pd.cut(df['message_length'], bins=3)

In [58]:
df.groupby('length_bin')['delivery_status'].mean()

length_bin
(49.75, 133.333]      0.480000
(133.333, 216.667]    0.436813
(216.667, 300.0]      0.440476
Name: delivery_status, dtype: float64

In [59]:
df.drop(['length_bin', 'rate_bin'], axis=1, inplace=True)

In [60]:
df.head()

,country,operator,sender_id,route,message_length,time_of_day,campaign_type,historical_delivery_rate,previous_failures,delivery_status
0,UK,vodafone,BANKTX,domestic,53,afternoon,promo,0.79,5,0
1,IN,jio,BANKTX,domestic,296,evening,alert,0.72,1,0
2,UK,jio,BANKTX,intl,196,afternoon,otp,0.62,3,0
3,UK,airtel,PAYAPP,domestic,278,night,alert,0.98,1,1
4,UK,vodafone,SHOPPY,intl,136,morning,otp,0.64,1,1

In [79]:
#data preprocessing
df.drop_duplicates()

,country,operator,sender_id,route,message_length,time_of_day,campaign_type,historical_delivery_rate,previous_failures,delivery_status
0,UK,vodafone,BANKTX,domestic,53,afternoon,promo,0.79,5,0
1,IN,jio,BANKTX,domestic,296,evening,alert,0.72,1,0
2,UK,jio,BANKTX,intl,196,afternoon,otp,0.62,3,0
3,UK,airtel,PAYAPP,domestic,278,night,alert,0.98,1,1
4,UK,vodafone,SHOPPY,intl,136,morning,otp,0.64,1,1
...,...,...,...,...,...,...,...,...,...,...
995,UK,airtel,SHOPPY,domestic,139,night,otp,0.79,1,1
996,UK,verizon,PAYAPP,domestic,105,night,alert,0.79,4,1
997,US,vodafone,SHOPPY,domestic,186,afternoon,otp,0.53,5,1
998,IN,vodafone,BANKTX,domestic,246,afternoon,otp,0.73,5,0
999,UK,verizon,SHOPPY,intl,70,afternoon,promo,0.84,3,0

In [80]:
df.isnull().sum()

country                     0
operator                    0
sender_id                   0
route                       0
message_length              0
time_of_day                 0
campaign_type               0
historical_delivery_rate    0
previous_failures           0
delivery_status             0
dtype: int64

# changing data, converting categorical features

In [61]:
df_encoded = pd.get_dummies(df, columns=[
    'country','operator','sender_id',
    'route','time_of_day','campaign_type'
])

In [62]:
df_encoded.head()

,message_length,historical_delivery_rate,previous_failures,delivery_status,country_IN,country_UK,country_US,operator_airtel,operator_jio,operator_verizon,...,sender_id_SHOPPY,route_domestic,route_intl,time_of_day_afternoon,time_of_day_evening,time_of_day_morning,time_of_day_night,campaign_type_alert,campaign_type_otp,campaign_type_promo
0,53,0.79,5,0,False,True,False,False,False,False,...,False,True,False,True,False,False,False,False,False,True
1,296,0.72,1,0,True,False,False,False,True,False,...,False,True,False,False,True,False,False,True,False,False
2,196,0.62,3,0,False,True,False,False,True,False,...,False,False,True,True,False,False,False,False,True,False
3,278,0.98,1,1,False,True,False,True,False,False,...,False,True,False,False,False,False,True,True,False,False
4,136,0.64,1,1,False,True,False,False,False,False,...,True,False,True,False,False,True,False,False,True,False

In [63]:
df_encoded.columns

Index(['message_length', 'historical_delivery_rate', 'previous_failures',
       'delivery_status', 'country_IN', 'country_UK', 'country_US',
       'operator_airtel', 'operator_jio', 'operator_verizon',
       'operator_vodafone', 'sender_id_BANKTX', 'sender_id_PAYAPP',
       'sender_id_SHOPPY', 'route_domestic', 'route_intl',
       'time_of_day_afternoon', 'time_of_day_evening', 'time_of_day_morning',
       'time_of_day_night', 'campaign_type_alert', 'campaign_type_otp',
       'campaign_type_promo'],
      dtype='str')

Making the data ready for training

In [64]:
X = df_encoded.drop(columns=['delivery_status'])
y = df_encoded['delivery_status']

In [65]:
X.head()

,message_length,historical_delivery_rate,previous_failures,country_IN,country_UK,country_US,operator_airtel,operator_jio,operator_verizon,operator_vodafone,...,sender_id_SHOPPY,route_domestic,route_intl,time_of_day_afternoon,time_of_day_evening,time_of_day_morning,time_of_day_night,campaign_type_alert,campaign_type_otp,campaign_type_promo
0,53,0.79,5,False,True,False,False,False,False,True,...,False,True,False,True,False,False,False,False,False,True
1,296,0.72,1,True,False,False,False,True,False,False,...,False,True,False,False,True,False,False,True,False,False
2,196,0.62,3,False,True,False,False,True,False,False,...,False,False,True,True,False,False,False,False,True,False
3,278,0.98,1,False,True,False,True,False,False,False,...,False,True,False,False,False,False,True,True,False,False
4,136,0.64,1,False,True,False,False,False,False,True,...,True,False,True,False,False,True,False,False,True,False

In [66]:
y.head()

0    0
1    0
2    0
3    1
4    1
Name: delivery_status, dtype: int64

In [67]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y   # VERY IMPORTANT
)

In [68]:
from xgboost import XGBClassifier

xgb = XGBClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=5,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric='logloss'
)

xgb.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, ...)

In [69]:
y_pred = xgb.predict(X_test)
y_prob = xgb.predict_proba(X_test)[:,1]

In [70]:
y_pred

array([1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 1])

In [71]:
from sklearn.metrics import accuracy_score, roc_auc_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_prob))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.69
ROC-AUC: 0.7406060606060606

Classification Report:
              precision    recall  f1-score   support

           0       0.72      0.72      0.72       110
           1       0.66      0.66      0.66        90

    accuracy                           0.69       200
   macro avg       0.69      0.69      0.69       200
weighted avg       0.69      0.69      0.69       200


Confusion Matrix:
[[79 31]
 [31 59]]

In [72]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.72      0.72      0.72       110
           1       0.66      0.66      0.66        90

    accuracy                           0.69       200
   macro avg       0.69      0.69      0.69       200
weighted avg       0.69      0.69      0.69       200

In [73]:
# trying some different model
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)

lr_pred = lr.predict(X_test)

In [74]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=6,
    random_state=42
)

rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)

In [75]:
from sklearn.metrics import classification_report

print("Logistic Regression:\n", classification_report(y_test, lr_pred))
print("Random Forest:\n", classification_report(y_test, rf_pred))
print("XGBoost:\n", classification_report(y_test, y_pred))

Logistic Regression:
               precision    recall  f1-score   support

           0       0.72      0.74      0.73       110
           1       0.67      0.66      0.66        90

    accuracy                           0.70       200
   macro avg       0.70      0.70      0.70       200
weighted avg       0.70      0.70      0.70       200

Random Forest:
               precision    recall  f1-score   support

           0       0.74      0.76      0.75       110
           1       0.70      0.68      0.69        90

    accuracy                           0.72       200
   macro avg       0.72      0.72      0.72       200
weighted avg       0.72      0.72      0.72       200

XGBoost:
               precision    recall  f1-score   support

           0       0.72      0.72      0.72       110
           1       0.66      0.66      0.66        90

    accuracy                           0.69       200
   macro avg       0.69      0.69      0.69       200
weighted avg       0.69      0.69      0.69       200

Random Forest performing Best

In [76]:
import pandas as pd

importance = pd.DataFrame({
    'feature': X_train.columns,
    'importance': rf.feature_importances_
}).sort_values(by='importance', ascending=False)

print(importance.head(10))

                     feature  importance
1   historical_delivery_rate    0.256570
21       campaign_type_promo    0.139231
0             message_length    0.114189
2          previous_failures    0.111211
20         campaign_type_otp    0.077713
19       campaign_type_alert    0.028320
6            operator_airtel    0.020031
15     time_of_day_afternoon    0.019300
13            route_domestic    0.018999
9          operator_vodafone    0.018915

In [78]:
#saving model
import joblib

joblib.dump(rf, "sms_model.pkl")
joblib.dump(X_train.columns.tolist(), "columns.pkl")

['columns.pkl']